"""rename departments

Revision ID: 796b572b299d
Revises: 3c9a0589d352
Create Date: 2024-06-27 10:43:19.869300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b572b299d'
down_revision = '3c9a0589d352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
